#80表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: config-consumer-order
  cloud:
    zookeeper:
      connect-string: 8.140.55.11:2181   #127.0.0.1:2181 # 192.168.111.144:2181 #

